### ISSUE TITLE
Se debe mejorar la presentación del código de producción

### ISSUE THREAD

**Issue by evolentini** [gaston-cb/testingDriversLeds#1]
El espaciado vertical no es uniforme

https://github.com/gaston-cb/testingDriversLeds/blob/eb381798b9777cdf27a53f68dc79ddc642956fcc/src/leds.c#L19-L22

https://github.com/gaston-cb/testingDriversLeds/blob/eb381798b9777cdf27a53f68dc79ddc642956fcc/src/leds.c#L49-L51

El uso de la llaves no es consistente

https://github.com/gaston-cb/testingDriversLeds/blob/eb381798b9777cdf27a53f68dc79ddc642956fcc/src/leds.c#L15-L17

**Comment by gaston-cb** [comment]
Hola, se acaba de mejorar este punto en el commit a322abb
