### ISSUE TITLE
Se podría implementar en forma más simple

### ISSUE THREAD

**Issue by evolentini** [gaston-cb/testingDriversLeds#2]
La función

https://github.com/gaston-cb/testingDriversLeds/blob/eb381798b9777cdf27a53f68dc79ddc642956fcc/src/leds.c#L54-L60

se podría implementar mas claramente de la siguiente forma

```c
uint8_t LedsState(uint8_t number_led) { 
    if(isValidNumberLed(number_led) == false) return -1; 
    uint16_t LedsState = (*puerto) & LedsToMask(number_led) ;
    return LedsState ? 1 : 0; 
}
```

**Comment by gaston-cb** [comment]
Se agregaron las sugerencias a las funciones
