### ISSUE TITLE
Hay pruebas que deberían reformularse

### ISSUE THREAD

**Issue by evolentini** [gaston-cb/testingDriversLeds#3]
En esta  prueba hay llamadas a funciones realmente no cambian el resultado de la misma. Si bien se podría pensar que esto sirve para obtener una implementación más robusta, la realidad es que solo agrega confusión.

https://github.com/gaston-cb/testingDriversLeds/blob/eb381798b9777cdf27a53f68dc79ddc642956fcc/test/test_leds.c#L104-L107

En esta prueba no se prueba adecuadamente que todos los leds se apaguen, sino que lo hacen solo los dos que fueron prendidos. Sería mejor prueba llamar a `LedsTurnOnAll()` antes de `LedsTurnOffAll()`.

https://github.com/gaston-cb/testingDriversLeds/blob/eb381798b9777cdf27a53f68dc79ddc642956fcc/test/test_leds.c#L114-L117

**Comment by gaston-cb** [comment]
Se cambio el test de prender todos los leds y apagar todos los leds usando las funciones LedsAllTurnOn y LedsAllTurnOff

https://github.com/gaston-cb/testingDriversLeds/blob/b94c70e6619ea4b2a9cfabcfcddc2556d7daebf0/test/test_leds.c#L102-L113

https://github.com/gaston-cb/testingDriversLeds/blob/b94c70e6619ea4b2a9cfabcfcddc2556d7daebf0/test/test_leds.c#L116-L127

**Comment by evolentini** [comment]
Se corrigió la calificación para contemplar las correcciones
